### ISSUE TITLE
Add null check back for sourcePerson in `src/main/java/org/trebol/jpa/services/conversion/CustomersConverterJpaServiceImpl.java`

### ISSUE THREAD

**Issue by mepox** [trebol-ecommerce/spring-boot-backend#223]
@bglamadrid @NyorJa 
Null check got removed in PR #193 , so after our discussion, should this added back then?
If yes, I will open another issue for the other similar PR, which is #190

**Comment by bglamadrid** [comment]
Services from package `org.trebol.jpa.services.conversion` are about to change due to refactoring in #227
This issue is going stale when that happens

In that PR, the `applyChangesToExistingEntity` method used to belong to this service, but that has been moved to a new one altogether; `CustomersDataTransportJpaServiceImpl`.

I've said before want to document this project better, and here's one important thing to note. Services in `org.trebol.jpa.services.crud` are the ones responsible for these kinds of validations. Other services must be designed dumber and so they are to assume all validations are made outside of their scope.

**Comment by bglamadrid** [comment]
Closing this issue for the reasons stated above.
